name: "Continuous Integration"

on:
  pull_request:
    branches:
      - "*.x"
      - "master"
  push:
    branches:
      - "*.x"
      - "master"
  schedule:
    - cron: "42 9 * * 1"

jobs:
  phpstan:
    name: "Static Analysis"
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        php-version:
          - "7.4"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v2"
        with:
          path: "~/.composer/cache"
          key: "php-${{ matrix.php-version }}-composer-locked-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-locked-"

      - name: "Install dependencies with composer"
        run: "composer install --no-interaction --no-progress --no-suggest --prefer-dist"

      - name: "Run PHPStan"
        run: "vendor/bin/phpstan"

  phpunit:
    name: "PHPUnit"
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        php-version:
          - "7.3"
          - "7.4"
          - "8.0"
        deps:
          - "lowest"
          - "latest"
        coverage:
          - "false"
        include:
          - php-version: "7.4"
            deps: "latest"
            coverage: "true"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "pcov"
          ini-values: "zend.assertions=1"
          extensions: "bcmath"

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v2"
        with:
          path: "~/.composer/cache"
          key: "php-${{ matrix.php-version }}-composer-locked-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-locked-"

      - name: "Install dependencies with composer"
        run: "composer install --no-interaction --no-progress --no-suggest --prefer-dist"
        if: "${{ matrix.deps != 'lowest' }}"

      - name: "Install lowest possible dependencies with composer"
        run: "composer update --no-interaction --no-progress --no-suggest --prefer-dist --prefer-lowest"
        if: "${{ matrix.deps == 'lowest' }}"

      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit -c phpunit.xml.dist"
        if: "${{ matrix.coverage != 'true' }}"

      - name: "Run PHPUnit with coverage"
        run: "vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage.xml"
        if: "${{ matrix.coverage == 'true' }}"

      - name: "Upload coverage"
        run: "wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover ./coverage.xml"
        if: "${{ matrix.coverage == 'true' }}"